### ISSUE TITLE
Obvious Virus

### ISSUE THREAD

**Issue by TheonlyIcebear** [PurgerDev/PurgeStealer#2]
The user PurgerDev definitely didn't code this especially considering the source code isn't C++ as he claims it was written in. It's a .rar file. Obvious skidding and inside there's literally a straight up exe. Also the user JUST joined github with NO PROFILE PICTURE. Just look at his activity. This is obviously a alt Account made specifically to create this virus

**Comment by PurgerDev** [comment]
Saying that I simply laughed at this message would be a huge understatement. I have to remind you that this isn't a daycare for children and in the future I won't tolerate any dumb spam coming from people.

This was coded in C++ and if you had known certain basics, you would be able to find that out by yourself. This software isn't open-source for certain reasons and I posted it on github because it's great for version control and suits my needs. Archiving it is just a convenient way of keeping it together.
